name: muslim_wallet
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4
  get_it: ^8.0.1
  bloc:
  flutter_bloc:
  equatable: 
  dio:
  freezed_annotation:
  json_annotation:
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  json_serializable:

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/images/
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 700


  uses-material-design: true